export const WORKS = [
  {
    slug: 'overleaf-claude-mcp',
    name: 'Overleaf Claude MCP',
    year: '2026',
    role: 'Developer',
    stack: 'TypeScript · Node · MCP · Playwright',
    client: 'Personal',
    tag: 'personal',
    description: 'an MCP server that lets Claude read, edit and compile Overleaf projects',
    brief: 'Claude edits your LaTeX paper on the Overleaf free tier.',
    body: [
      'Overleaf keeps the Git bridge and Dropbox sync behind Premium, so the free tier has no public API. This server speaks the same internal HTTP and socket endpoints the Overleaf web app uses, authenticated with a browser session cookie you paste once.',
      'Twenty eight tools cover the whole loop: list and select a project, read the LaTeX and the figures, grep across files, write and edit, upload, rename, move, compile server side, read the parsed error log with file and line, and pull the PDF back.',
      'It also runs prose through free AI content detectors and checks it for plagiarism, reporting which sentence, in which file, on which line was flagged.',
      'MIT licensed, Node 20 or newer, with CI on every push and a release workflow that publishes to npm on tag.',
    ],
    result: '28 tools',
    tone: 'navy',
    stills: ['Repository', 'Tool surface', 'CI runs'],
    cover: '/shots/overleaf-claude-mcp-1.webp',
    images: [
      '/shots/overleaf-claude-mcp-1.webp',
      '/shots/overleaf-claude-mcp-2.webp',
      '/shots/overleaf-claude-mcp-3.webp',
    ],
    repo: 'https://github.com/MarvelCollin/overleaf-claude-mcp',
  },
  {
    slug: 'itel',
    name: 'NRX',
    year: '2026',
    role: 'Fullstack',
    stack: 'Next.js · React 19 · Go · PostgreSQL',
    client: 'NRX Solution',
    tag: 'client',
    description: 'an ISO compliance management platform',
    brief: 'Compliance frameworks, evidence and audits in one workspace.',
    body: [
      'NRX turns scattered spreadsheets, screenshots and chat threads into a single workspace for incidents, assets, people and controls, aimed at teams working toward SOC 2, ISO 27001 and GDPR.',
      'The frontend is Next.js 16 on the App Router with React 19, TanStack Query over a single axios client, SSE driven notifications and an embedded OnlyOffice editor with a word level document diff for the policy library.',
      'The backend is Go and Gin in clean architecture layers with Wire dependency injection, GORM against PostgreSQL, Redis caching, JWT auth over httpOnly cookies, Azure Blob storage for uploads and generated swagger docs.',
      'Live at itel.stevenlie.my.id with a staging environment alongside it. The frontend unit suite runs 386 Vitest tests plus Playwright end to end specs.',
    ],
    result: '386 tests green',
    tone: 'slate',
    stills: ['Landing', 'Document compare', 'Compliance'],
    cover: '/shots/itel-1.webp',
    images: ['/shots/itel-1.webp', '/shots/itel-2.webp'],
  },
  {
    slug: 'mnemosyne',
    name: 'Mnemosyne',
    year: '2026',
    role: 'Solo',
    stack: 'React 19 · TypeScript · Vite',
    client: 'Personal',
    tag: 'personal',
    description: 'a browser PDF reader that remembers where you stopped',
    brief: 'Your reading library, in the browser.',
    body: [
      'Named after the goddess of memory. Open a PDF or paste a Google Drive link and it renders in the browser with zoom, page navigation, auto scroll and keyboard shortcuts.',
      'Reading position and progress persist per document, so reopening a file resumes where you left off. There is an inline translation popup and a light and dark theme.',
      'React 19, TypeScript, Vite and Tailwind v4 with react-pdf for rendering, linted with oxlint and covered by 39 Vitest tests. Deployed to GitHub Pages on every push to main.',
    ],
    result: '39 tests green',
    tone: 'sage',
    stills: ['Library', 'Reader', 'Drive import'],
    cover: '/shots/mnemosyne-1.webp',
    images: ['/shots/mnemosyne-1.webp'],
    repo: 'https://github.com/MarvelCollin/Mnemosyne',
  },
  {
    slug: 'subfreeze-netflix',
    name: 'SubFreeze Netflix',
    year: '2026',
    role: 'Solo',
    stack: 'JavaScript · Manifest V3',
    client: 'Personal',
    tag: 'personal',
    description: 'a Netflix extension for dual subtitles and frozen lines',
    brief: 'Two subtitle languages at once, frozen where you need them.',
    body: [
      'A browser extension that shows two subtitle languages side by side, freezes a line on screen so it stays readable, and adds precision seek controls for replaying a phrase.',
      'Built for language learning. Plain JavaScript with no build step: a background service worker plus eleven content scripts injected into the page world at document start, with an isolated world bridge for messaging.',
      'Translation goes through the Google translate endpoint on demand. Loads unpacked in Chrome or Firefox.',
    ],
    result: 'Open source',
    tone: 'vermillion',
    stills: ['Repository', 'Overlay', 'Controls'],
    cover: '/shots/subfreeze-1.webp',
    images: ['/shots/subfreeze-1.webp'],
    repo: 'https://github.com/MarvelCollin/SubFreezeNetflix',
  },
  {
    slug: 'minecraft-server',
    name: 'Minecraft Server',
    year: '2026',
    role: 'Solo',
    stack: 'Docker · Bash',
    client: 'Personal',
    tag: 'personal',
    description: 'a self hosted Minecraft server with one command control',
    brief: 'Dockerized Minecraft with backups, mods and RCON.',
    body: [
      'A single Bash CLI wraps Docker Compose with about twenty subcommands: a setup wizard, start and stop, logs, an RCON console, a Modrinth aware mod manager, backup and restore, and player admin for op, kick, ban and whitelist.',
      'Compose runs three services: the server itself, a backup sidecar doing interval snapshots with day based pruning, and an optional playit.gg tunnel agent for exposing the server from behind CGNAT.',
      'Server type, version, memory, difficulty, gamerules and the mod list all come from environment variables, with gamerules applied at boot over RCON.',
    ],
    result: 'Open source',
    tone: 'sage',
    stills: ['Repository', 'CLI', 'Compose'],
    cover: '/shots/mcserver-1.webp',
    images: ['/shots/mcserver-1.webp'],
    repo: 'https://github.com/MarvelCollin/minecraft-server',
  },
  {
    slug: 'user-testing-skills',
    name: 'User Testing Skills',
    year: '2026',
    role: 'Solo',
    stack: 'Claude Code plugin · Markdown · Bash',
    client: 'Personal',
    tag: 'personal',
    description: 'a Claude Code plugin that audits sites like a real user',
    brief: 'Six commands that walk a site and report what breaks.',
    body: [
      'A plugin that role plays a human user to audit a website, exposing six commands: a full audit, a goal driven flow test, a WCAG accessibility pass, a head to head comparison, an AI slop design detector and a report compiler.',
      'The full audit takes focus areas for navigation, mobile, forms, accessibility, privacy, performance, errors, dark mode, 404 handling and design slop, and returns a scored report with prioritised findings.',
      'Skill definitions in markdown with paired bash and PowerShell wrappers around axe, Lighthouse and a performance check.',
    ],
    result: 'Open source',
    tone: 'plum',
    stills: ['Repository', 'Commands', 'Report'],
    cover: '/shots/uxskills-1.webp',
    images: ['/shots/uxskills-1.webp'],
    repo: 'https://github.com/MarvelCollin/user-testing-skills',
  },
  {
    slug: 'misvord',
    repo: 'https://github.com/MarvelCollin/MisVord',
  },
  {
    slug: 'pomolab',
    repo: 'https://github.com/MarvelCollin/Pomolab',
  },
  {
    slug: 'constellation',
    cover: '/shots/constellation-1.webp',
    images: ['/shots/constellation-1.webp'],
    repo: 'https://github.com/MarvelCollin/Constellation',
  },
  {
    slug: 'livora',
    cover: '/shots/livora-1.webp',
    images: ['/shots/livora-1.webp'],
    repo: 'https://github.com/MarvelCollin/Livora',
  },
  {
    slug: 'devora',
    cover: '/shots/devora-1.webp',
    images: ['/shots/devora-1.webp', '/shots/devora-2.webp'],
    repo: 'https://github.com/MarvelCollin/Devora',
  },
  {
    slug: 'claudecron',
    cover: '/shots/claudecron-1.webp',
    images: ['/shots/claudecron-1.webp'],
    repo: 'https://github.com/MarvelCollin/ClaudeCron',
  },
  {
    slug: 'knowledge-distillation',
    cover: 'https://raw.githubusercontent.com/MarvelCollin/knowledge-distillation-quantization/main/figures/fig1_methods_ceiling.png',
    images: [
      'https://raw.githubusercontent.com/MarvelCollin/knowledge-distillation-quantization/main/figures/fig1_methods_ceiling.png',
      'https://raw.githubusercontent.com/MarvelCollin/knowledge-distillation-quantization/main/figures/fig2_gap_study.png',
      'https://raw.githubusercontent.com/MarvelCollin/knowledge-distillation-quantization/main/figures/fig3_quantization.png',
      'https://raw.githubusercontent.com/MarvelCollin/knowledge-distillation-quantization/main/figures/fig4_int4_failure_mode.png',
      'https://raw.githubusercontent.com/MarvelCollin/knowledge-distillation-quantization/main/figures/fig5_failure_mixture.png',
    ],
    repo: 'https://github.com/MarvelCollin/knowledge-distillation-quantization',
  },
  {
    slug: 'adobe-premiere-mcp',
    name: 'Adobe Premiere MCP',
    year: '2026',
    role: 'Solo',
    stack: 'TypeScript · Node · MCP · CEP',
    client: 'Personal',
    tag: 'personal',
    description: 'an MCP server that drives Adobe Premiere Pro',
    brief: 'Cut, grade and export in Premiere from an AI assistant.',
    body: [
      'An MCP server for driving Adobe Premiere Pro from an AI assistant: inspect a project, cut and arrange a timeline, grade by measurement rather than by eye, mix and normalise audio to a real loudness target, and export frames or finished video.',
      'The design rule is one tool per expert capability, not one per API call. analyse_clips renders each shot, isolates it from the tracks above and reports its black point, contrast and colour cast, so a grade follows numbers rather than a hunch. analyse_loudness measures true LUFS to ITU-R BS.1770, a figure Premiere exposes to no script at all.',
      'Every write verifies itself. A tool reads the value back, and the ones that cannot be checked say so rather than reporting a cheerful success, because several Premiere scripting calls return No Error while doing nothing.',
      'The CEP panel that carries commands into Premiere was written from the protocol and signed with its own certificate. MIT licensed, published to npm and verified against Premiere Pro 26.2 on Windows.',
    ],
    result: 'Verified on 26.2',
    tone: 'plum',
    stills: ['Repository', 'Panel', 'Tools'],
    repo: 'https://github.com/MarvelCollin/adobe-premiere-cc-mcp',
  },
  {
    slug: 'polaris',
    name: 'Polaris',
    year: '2026',
    role: 'Solo',
    stack: 'Tauri 2 · React 19 · TypeScript · SQLite',
    client: 'Sahabat Sentarum',
    tag: 'client',
    description: 'a point of sale desktop app that works offline',
    brief: 'Offline first point of sale with cloud sync.',
    body: [
      'A point of sale desktop app for Sahabat Sentarum. Tauri 2 with React 19 and TypeScript over a local SQLite database that syncs to Turso as an embedded replica, so the shop keeps selling when the connection drops.',
      'Sales and purchasing with returns and partial payments, customer accounts with per customer pricing, product and category management with images, receivables and payables tracking, and a dashboard.',
      'ESC/POS thermal receipt printing, QRIS payments through Midtrans, automatic Google Drive backups and in app updates driven by a signed manifest.',
      'Release credentials are compiled in from a gitignored secrets file, so installers ship from a private dist repository rather than from source.',
    ],
    result: 'v2.12 shipping',
    tone: 'ocean',
    stills: ['Dashboard', 'Sales', 'Receipts'],
    cover: '/shots/polaris-1.png',
    images: ['/shots/polaris-1.png'],
    repo: 'https://github.com/MarvelCollin/Polaris',
  },
  {
    slug: 'queueoverflow',
    name: 'QueueOverflow',
    year: '2026',
    role: 'Solo',
    stack: 'Tauri · React · Sea ORM · PostgreSQL',
    client: 'Personal',
    tag: 'product',
    description: 'a question and answer board built as a queue',
    brief: 'Stack Overflow, if answering were a queue.',
    body: [
      'A question and answer board that treats unanswered questions as a queue rather than a feed, so the oldest unanswered post surfaces first instead of the loudest one.',
      'A Rust backend on Sea ORM against PostgreSQL, wrapped in Tauri and paired with a React and TypeScript frontend on Vite.',
      'Runs from Docker Compose with a dedicated Dockerfile for the API, and Cypress end to end specs cover the main flows.',
    ],
    result: 'Open source',
    tone: 'rose',
    stills: ['Questions', 'Answers', 'Queue'],
    cover: '/shots/queueoverflow-1.png',
    images: ['/shots/queueoverflow-1.png', '/shots/queueoverflow-2.png'],
    repo: 'https://github.com/MarvelCollin/QueueOverflow',
  },
  {
    slug: 'model-quantization',
    name: 'Quantization and Explainability',
    year: '2026',
    role: 'Solo · Research',
    stack: 'Python · PyTorch · IndoBERT · LIME · SHAP',
    client: 'ICCSCI 2025',
    tag: 'personal',
    description: 'a study of what quantization does to model explanations',
    brief: 'A compressed model still predicts. Does it still reason?',
    body: [
      'Most quantization papers report accuracy, latency and model size. This one asks a different question: after you quantize an Indonesian sentiment classifier, does it still give the same reasons for its predictions?',
      'The pipeline fine tunes IndoBERT on the SmSA three class sentiment task from IndoNLU, then produces eight deployment variants across post training quantization and quantization aware training.',
      'Every variant is measured on task performance, calibration error, explanation stability across LIME, SHAP, Occlusion and Integrated Gradients, and explanation faithfulness, so that a stable explanation is not just stably wrong. Stability is bootstrapped and Bonferroni corrected.',
      'On top sit robustness stress tests, an Indonesian linguistic probe suite covering negation scope, reduplication, hedging and contrastive markers, and a deployment recommender that ranks the eight variants under configurable constraints.',
    ],
    result: 'Accepted at ICCSCI 2025',
    tone: 'navy',
    stills: ['LIME comparison', 'Attribution shift', 'Variants'],
    cover: '/shots/model-quantization-1.png',
    images: ['/shots/model-quantization-1.png', '/shots/model-quantization-2.png'],
    repo: 'https://github.com/Wenfuuu/model-quantization-sentiment-analysis',
  },
];
