export const WORKS = [
  {
    slug: 'overleaf-claude-mcp',
    name: 'Overleaf Claude MCP',
    year: '2026',
    role: 'Developer',
    stack: 'TypeScript · Node · MCP · Playwright',
    client: 'Personal',
    tag: 'personal',
    description: 'an MCP server that lets Claude read, edit and compile Overleaf projects',
    brief: 'Claude edits your LaTeX paper on the Overleaf free tier.',
    body: [
      'Overleaf keeps the Git bridge and Dropbox sync behind Premium, so the free tier has no public API. This server speaks the same internal HTTP and socket endpoints the Overleaf web app uses, authenticated with a browser session cookie you paste once.',
      'Twenty eight tools cover the whole loop: list and select a project, read the LaTeX and the figures, grep across files, write and edit, upload, rename, move, compile server side, read the parsed error log with file and line, and pull the PDF back.',
      'It also runs prose through free AI content detectors and checks it for plagiarism, reporting which sentence, in which file, on which line was flagged.',
      'MIT licensed, Node 20 or newer, with CI on every push and a release workflow that publishes to npm on tag.',
    ],
    result: '28 tools',
    tone: 'navy',
    stills: ['Repository', 'Tool surface', 'CI runs'],
    cover: '/shots/overleaf-claude-mcp-1.webp',
    images: [
      '/shots/overleaf-claude-mcp-1.webp',
      '/shots/overleaf-claude-mcp-2.webp',
      '/shots/overleaf-claude-mcp-3.webp',
    ],
    repo: 'https://github.com/MarvelCollin/overleaf-claude-mcp',
  },
  {
    slug: 'kolinrelics',
    cover: '/shots/kolinrelics-1.webp',
    images: ['/shots/kolinrelics-1.webp'],
    repo: 'https://github.com/MarvelCollin/KolinRelics',
  },
  {
    slug: 'itel',
    name: 'ITEL',
    year: '2026',
    role: 'Fullstack',
    stack: 'Next.js · React 19 · Go · PostgreSQL',
    client: 'NRX Solution',
    tag: 'client',
    description: 'an ISO compliance management platform',
    brief: 'Compliance frameworks, evidence and audits in one workspace.',
    body: [
      'ITEL turns scattered spreadsheets, screenshots and chat threads into a single workspace for incidents, assets, people and controls, aimed at teams working toward SOC 2, ISO 27001 and GDPR.',
      'The frontend is Next.js 16 on the App Router with React 19, TanStack Query over a single axios client, SSE driven notifications and an embedded OnlyOffice editor with a word level document diff for the policy library.',
      'The backend is Go and Gin in clean architecture layers with Wire dependency injection, GORM against PostgreSQL, Redis caching, JWT auth over httpOnly cookies, Azure Blob storage for uploads and generated swagger docs.',
      'Live at itel.stevenlie.my.id with a staging environment alongside it. The frontend unit suite runs 386 Vitest tests plus Playwright end to end specs.',
    ],
    result: '386 tests green',
    tone: 'slate',
    stills: ['Landing', 'Document compare', 'Compliance'],
    cover: '/shots/itel-1.webp',
    images: ['/shots/itel-1.webp', '/shots/itel-2.webp'],
  },
  {
    slug: 'careerlink',
    name: 'CareerLink',
    year: '2026',
    role: 'Fullstack',
    stack: 'Laravel · React 19 · React Router 7',
    client: 'BINUS University',
    tag: 'client',
    description: 'an internship and career platform for students',
    brief: 'Student career tracking, bootcamps and certificates.',
    body: [
      'CareerLink runs the BINUS Enrichment internship programme: student master data, announcements, bootcamps with categories and enrollments, session attendance and evaluation, progress reports and certificate generation.',
      'A Laravel 12 API on PHP 8.2 backs a React 19 frontend on React Router 7 with server side rendering, Tailwind v4 and Radix, with xlsx and html2canvas export for the reporting side.',
      'Deployed with Docker Compose behind the campus host enrichment-socs.apps.binus.ac.id.',
    ],
    result: 'In production',
    tone: 'navy',
    stills: ['Bootcamps', 'Sign in', 'Reports'],
    cover: '/shots/careerlink-1.webp',
    images: ['/shots/careerlink-1.webp', '/shots/careerlink-2.webp'],
    repo: 'https://github.com/enrichment-socs/career-link-fe',
  },
  {
    slug: 'attendance-management',
    name: 'Attendance Management',
    year: '2026',
    role: 'Fullstack',
    stack: 'Express · Prisma · Socket.IO · React 19',
    client: 'BINUS University',
    tag: 'client',
    description: 'geofenced attendance tracking for campus programmes',
    brief: 'Attendance that checks where you actually are.',
    body: [
      'Students check in from the browser and the server verifies the coordinates against per campus bounds with geolib, so attendance cannot be marked from off site.',
      'Express and Prisma back the API with Socket.IO pushing live session state, JWT and bcrypt for auth, ExcelJS export for reports, nodemailer for notices and Winston for structured logs. The frontend is React 19 on Vite with socket.io-client.',
      'Covers the Anggrek, Alam Sutera, Semarang, Bandung, Malang and Bekasi campuses, deployed with Docker Compose on the campus host.',
    ],
    result: 'In production',
    tone: 'ocean',
    stills: ['Sign in', 'Sessions', 'Reports'],
    cover: '/shots/attendance-1.webp',
    images: ['/shots/attendance-1.webp'],
  },
  {
    slug: 'hiring-system',
    name: 'Hiring System',
    year: '2026',
    role: 'Fullstack',
    stack: '.NET 10 · Next.js 16 · PostgreSQL · RabbitMQ',
    client: 'Boleh Jadi Wirausaha',
    tag: 'client',
    description: 'an applicant tracking system for recruitment',
    brief: 'Job openings, candidates, reviews and interviews end to end.',
    body: [
      'A recruitment platform covering job openings and categories, candidate profiles, applications, review queues, skill tests, interview invitations and an activity log dashboard.',
      'The backend is .NET 10 in clean architecture with EF Core migrations, JWT auth behind a permission policy provider, PostgreSQL, Redis caching, RabbitMQ entity sync and a pluggable file store for CV uploads that serves documents only through a guarded download route.',
      'The frontend is Next.js 16 and React 19 with Tailwind v4, react hook form and zod, zustand state and server sent events for notifications, shipped as a standalone build with a strict security header set.',
      '585 frontend tests and 229 backend tests run green, alongside k6 load tests and Lighthouse audits.',
    ],
    result: '814 tests green',
    tone: 'paper',
    stills: ['Dashboard', 'Candidates', 'Interviews'],
    cover: '/shots/hiring-system-1.webp',
    images: ['/shots/hiring-system-1.webp'],
  },
  {
    slug: 'mnemosyne',
    name: 'Mnemosyne',
    year: '2026',
    role: 'Solo',
    stack: 'React 19 · TypeScript · Vite',
    client: 'Personal',
    tag: 'personal',
    description: 'a browser PDF reader that remembers where you stopped',
    brief: 'Your reading library, in the browser.',
    body: [
      'Named after the goddess of memory. Open a PDF or paste a Google Drive link and it renders in the browser with zoom, page navigation, auto scroll and keyboard shortcuts.',
      'Reading position and progress persist per document, so reopening a file resumes where you left off. There is an inline translation popup and a light and dark theme.',
      'React 19, TypeScript, Vite and Tailwind v4 with react-pdf for rendering, linted with oxlint and covered by 39 Vitest tests. Deployed to GitHub Pages on every push to main.',
    ],
    result: '39 tests green',
    tone: 'sage',
    stills: ['Library', 'Reader', 'Drive import'],
    cover: '/shots/mnemosyne-1.webp',
    images: ['/shots/mnemosyne-1.webp'],
    repo: 'https://github.com/MarvelCollin/Mnemosyne',
  },
  {
    slug: 'subfreeze-netflix',
    name: 'SubFreeze Netflix',
    year: '2026',
    role: 'Solo',
    stack: 'JavaScript · Manifest V3',
    client: 'Personal',
    tag: 'personal',
    description: 'a Netflix extension for dual subtitles and frozen lines',
    brief: 'Two subtitle languages at once, frozen where you need them.',
    body: [
      'A browser extension that shows two subtitle languages side by side, freezes a line on screen so it stays readable, and adds precision seek controls for replaying a phrase.',
      'Built for language learning. Plain JavaScript with no build step: a background service worker plus eleven content scripts injected into the page world at document start, with an isolated world bridge for messaging.',
      'Translation goes through the Google translate endpoint on demand. Loads unpacked in Chrome or Firefox.',
    ],
    result: 'Open source',
    tone: 'vermillion',
    stills: ['Repository', 'Overlay', 'Controls'],
    cover: '/shots/subfreeze-1.webp',
    images: ['/shots/subfreeze-1.webp'],
    repo: 'https://github.com/MarvelCollin/SubFreezeNetflix',
  },
  {
    slug: 'minecraft-server',
    name: 'Minecraft Server',
    year: '2026',
    role: 'Solo',
    stack: 'Docker · Bash',
    client: 'Personal',
    tag: 'personal',
    description: 'a self hosted Minecraft server with one command control',
    brief: 'Dockerized Minecraft with backups, mods and RCON.',
    body: [
      'A single Bash CLI wraps Docker Compose with about twenty subcommands: a setup wizard, start and stop, logs, an RCON console, a Modrinth aware mod manager, backup and restore, and player admin for op, kick, ban and whitelist.',
      'Compose runs three services: the server itself, a backup sidecar doing interval snapshots with day based pruning, and an optional playit.gg tunnel agent for exposing the server from behind CGNAT.',
      'Server type, version, memory, difficulty, gamerules and the mod list all come from environment variables, with gamerules applied at boot over RCON.',
    ],
    result: 'Open source',
    tone: 'sage',
    stills: ['Repository', 'CLI', 'Compose'],
    cover: '/shots/mcserver-1.webp',
    images: ['/shots/mcserver-1.webp'],
    repo: 'https://github.com/MarvelCollin/minecraft-server',
  },
  {
    slug: 'user-testing-skills',
    name: 'User Testing Skills',
    year: '2026',
    role: 'Solo',
    stack: 'Claude Code plugin · Markdown · Bash',
    client: 'Personal',
    tag: 'personal',
    description: 'a Claude Code plugin that audits sites like a real user',
    brief: 'Six commands that walk a site and report what breaks.',
    body: [
      'A plugin that role plays a human user to audit a website, exposing six commands: a full audit, a goal driven flow test, a WCAG accessibility pass, a head to head comparison, an AI slop design detector and a report compiler.',
      'The full audit takes focus areas for navigation, mobile, forms, accessibility, privacy, performance, errors, dark mode, 404 handling and design slop, and returns a scored report with prioritised findings.',
      'Skill definitions in markdown with paired bash and PowerShell wrappers around axe, Lighthouse and a performance check.',
    ],
    result: 'Open source',
    tone: 'plum',
    stills: ['Repository', 'Commands', 'Report'],
    cover: '/shots/uxskills-1.webp',
    images: ['/shots/uxskills-1.webp'],
    repo: 'https://github.com/MarvelCollin/user-testing-skills',
  },
  {
    slug: 'misvord',
    repo: 'https://github.com/MarvelCollin/MisVord',
  },
  {
    slug: 'pomolab',
    repo: 'https://github.com/MarvelCollin/Pomolab',
  },
  {
    slug: 'constellation',
    cover: '/shots/constellation-1.webp',
    images: ['/shots/constellation-1.webp'],
    repo: 'https://github.com/MarvelCollin/Constellation',
  },
  {
    slug: 'quizlingo',
    cover: '/shots/quizlingo-2.webp',
    images: ['/shots/quizlingo-2.webp', '/shots/quizlingo-1.webp'],
    repo: 'https://github.com/MarvelCollin/QuizLingo',
  },
  {
    slug: 'livora',
    cover: '/shots/livora-1.webp',
    images: ['/shots/livora-1.webp'],
    repo: 'https://github.com/MarvelCollin/Livora',
  },
  {
    slug: 'devora',
    cover: '/shots/devora-1.webp',
    images: ['/shots/devora-1.webp', '/shots/devora-2.webp'],
    repo: 'https://github.com/MarvelCollin/Devora',
  },
  {
    slug: 'claudecron',
    cover: '/shots/claudecron-1.webp',
    images: ['/shots/claudecron-1.webp'],
    repo: 'https://github.com/MarvelCollin/ClaudeCron',
  },
  {
    slug: 'knowledge-distillation',
    cover: 'https://raw.githubusercontent.com/MarvelCollin/knowledge-distillation-quantization/main/figures/fig1_methods_ceiling.png',
    images: [
      'https://raw.githubusercontent.com/MarvelCollin/knowledge-distillation-quantization/main/figures/fig1_methods_ceiling.png',
      'https://raw.githubusercontent.com/MarvelCollin/knowledge-distillation-quantization/main/figures/fig2_gap_study.png',
      'https://raw.githubusercontent.com/MarvelCollin/knowledge-distillation-quantization/main/figures/fig3_quantization.png',
      'https://raw.githubusercontent.com/MarvelCollin/knowledge-distillation-quantization/main/figures/fig4_int4_failure_mode.png',
      'https://raw.githubusercontent.com/MarvelCollin/knowledge-distillation-quantization/main/figures/fig5_failure_mixture.png',
    ],
    repo: 'https://github.com/MarvelCollin/knowledge-distillation-quantization',
  },
];
